
<?php


?>


<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Registration form</title>

    <!-- Icons font CSS-->
    <link href="vend/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vend/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="vend/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vend/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="cs/main.css" rel="stylesheet" media="all">
</head>
<style>
    table{
    
    margin-left:30px;
}
body,
    html {
        margin: 0;
        padding: 0;
        height: 100%;
        background: #60a3bc !important;
    }
    .btn--red {
  background: #0f89da;
}

.btn--red:hover {
  background: #b8e8fc;
}
.card-heading h2{
    color:white;
    font-size:20px;
    font-family:"Lucida Console", Monaco, monospace;
    text-align:center;
    text-transform: uppercase;
    

}

</style>

<body class="bg-gra-01">
    

        <div class="wrapper wrapper--w790">
            <div class="card card-5">
           
            <div class="card-heading">
                    <h2>Registration d'un nouveau employé</h2>
                </div>
            
     
                <div class="card-body">
                    <form method="POST">
                        <div class="form-row m-b-55">
                            <div class="name">Nom

                            </div>
                            <div class="value">
                                <div class="row row-space">
                                
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="firstName"  autocomplete="off" required>
                                            <label class="label--desc">Nom</label>
                                            <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
                                       
                                    </div>
                                
                                        <div class="input-group-desc">
                                            <input class="input--style-5" type="text" name="lastName" autocomplete="off" required >
                                            <label class="label--desc">Prénom</label>
                                            <span class="text-danger"><?php if (isset($name_error)) echo $name_error; ?></span>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>

                        
                        <div class="form-row">
                            <div class="name">Email</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="email" name="email" autocomplete="off" >
                                    <span class="text-danger"><?php if (isset($email_error)) echo $email_error; ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Mot de passe</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="password" name="password" autocomplete="off" >
                                    <span class="text-danger"><?php if (isset($password_error)) echo $password_error; ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Confirmer mot de passe</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="password" name="cpassword" autocomplete="off" >
                                    <span class="text-danger"><?php if (isset($cpassword_error)) echo $cpassword_error; ?></span>
                                </div>
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="name">Nom d'utilisateur</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="username" autocomplete="off" required >
                                    <span class="text-danger"><?php if (isset($username_error)) echo $username_error; ?></span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="name">Employé code</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="empcode" autocomplete="off" required >
                                
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Addresse</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="address" autocomplete="off" required >
                                    <span class="text-danger"><?php if (isset($ville_error)) echo $ville_error; ?></span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="name">Telephone</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="text" name="mobileno" autocomplete="off" required >
                                      <span class="text-danger"><?php if (isset($telephone_error)) echo $telephone_error; ?></span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="name">Date de naissance</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-5" type="date" class="datepicker" name="dob"  autocomplete="off" required >
                                </div>
                            </div>
                        </div>


                      
                        <div class="form-row">
                            <div class="name">Sexe</div>
                            <div class="value">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
                                        <select name="gender">
                        
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                         <option value="Other">Other</option>
                                        </select>
                                        <div class="select-dropdown"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                             
                        <div class="form-row">
                            <div class="name">Departement</div>
                            <div class="value">
                                <div class="input-group">
                                    <div class="rs-select2 js-select-simple select--no-search">
<select  name="department" autocomplete="off">

<?php
$use = new User;
$query=$use->departement();
$results=$query->fetchAll(PDO::FETCH_OBJ);
$cnt=1;

if($query->rowCount() > 0)
{
foreach($results as $resultt)
{   ?>                                            
<option value="<?php echo htmlentities($resultt->depname);?>"><?php echo htmlentities($resultt->depname);?></option>
<?php }} ?>
</select>
<div class="select-dropdown"></div>
</div>
                                </div>
                            </div>
                        </div>


                            <button class="btn btn--radius-2 btn--red" type="submit" name="register">Register</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



  <!-- Jquery JS-->
  <script src="vend/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="vend/select2/select2.min.js"></script>
    <script src="vend/datepicker/moment.min.js"></script>
    <script src="vend/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="j/global.js"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
</html>
<!-- end document-->
